# Generated by Django 5.2.16 on 2026-07-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='codigo_tipo_punto_venta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Punto Venta Comisionista'), (2, 'Punto Venta Ventanilla de Cobranza'), (3, 'Punto de Venta Móviles'), (4, 'Punto de Venta YPFB'), (5, 'Punto de Venta Cajeros'), (6, 'Punto de Venta Conjunta')], default=3, help_text='Tipo de punto de venta exigido por el servicio registroPuntoVenta del SIN.'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fecha_vigencia_cuis',
            field=models.DateTimeField(blank=True, help_text="Fecha de vencimiento del CUIS (dato 'fechaVigencia' que devuelve el SIN). El CUIS se puede renovar desde 5 dias antes de esta fecha.", null=True),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='codigo_punto_venta',
            field=models.PositiveIntegerField(help_text='Codigo de punto de venta. IMPORTANTE: en la integracion real este codigo lo ASIGNA el SIN como respuesta del servicio registroPuntoVenta, no se elige a mano. Mientras tanto se carga manualmente para poder armar la configuracion local.'),
        ),
    ]
