# Generated by Django 5.2.16 on 2026-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0002_puntoventa_codigo_tipo_punto_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_sistema',
            field=models.CharField(blank=True, help_text='Codigo que asigna el SIN al aprobar la Autorizacion de Sistemas. Vacio hasta completar ese tramite.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_autorizacion_sistema',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Se usa en el encabezado de las facturas impresas/PDF.', null=True, upload_to='empresa/logos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_sistema',
            field=models.CharField(blank=True, help_text='Nombre del sistema informatico tal como se declara ante el SIN.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_autorizacion',
            field=models.CharField(choices=[('Propietario', 'Propietario (uso exclusivo propio)'), ('Proveedor', 'Proveedor (ofrece el sistema a terceros)')], default='Propietario', help_text="Propietario: este NIT usa el sistema solo para si mismo. Proveedor: se ofrece el sistema a otros contribuyentes (estos se vinculan despues via 'Asociacion', un tramite mas simple que una autorizacion completa nueva).", max_length=15),
        ),
        migrations.AddField(
            model_name='empresa',
            name='version_sistema',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
