# Generated by Django 5.2.16 on 2026-08-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0003_empresa_codigo_sistema_empresa_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='municipio',
            field=models.CharField(blank=True, help_text="Municipio (distinto del departamento) — obligatorio para el XML de factura electrónica. Ej: depto 'Santa Cruz', municipio 'Santa Cruz de la Sierra'.", max_length=100, null=True),
        ),
    ]
