# Generated by Django 5.2.16 on 2026-08-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0004_sucursal_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='banco_qr',
            field=models.CharField(blank=True, help_text='Nombre del banco emisor del QR de cobro (solo informativo, se muestra junto al QR en el recibo).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='qr_cobro',
            field=models.ImageField(blank=True, help_text='Imagen del QR de cobro estatico (QR Simple) solicitado al banco. Se muestra en el recibo de venta para que el cliente pueda escanearlo y transferir el monto a mano (el QR estatico no lleva el monto incrustado).', null=True, upload_to='empresa/qr_cobro/'),
        ),
    ]
