# Generated by Django 5.2.16 on 2026-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0005_empresa_banco_qr_empresa_qr_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='descripcion',
            field=models.CharField(blank=True, help_text="Descripcion del punto de venta -- campo 'descripcion' exigido por separado del nombre en registroPuntoVenta.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='codigo_punto_venta',
            field=models.PositiveIntegerField(help_text='Codigo de punto de venta que ASIGNA el SIN como respuesta del servicio registroPuntoVenta -- se completa solo al guardar un punto de venta nuevo, no se elige a mano.'),
        ),
    ]
