# Generated by Django 5.2.16 on 2026-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0006_puntoventa_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='codigo_cuis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='fecha_autorizacion_cuis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='fecha_vigencia_cuis',
            field=models.DateTimeField(blank=True, help_text="Fecha de vencimiento del CUIS de este punto de venta (dato 'fechaVigencia' que devuelve el SIN). Renovable desde 5 dias antes de esta fecha.", null=True),
        ),
    ]
