# Generated by Django 5.2.16 on 2026-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0007_puntoventa_codigo_cuis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial')], default='COMERCIAL', help_text="Se define al registrar la empresa, no se espera que cambie despues. Determina como se calcula Producto.costo_actual SOLO cuando se registra una entrada por motivo 'Producción Interna': Comercial usa Costo Promedio Ponderado (igual que Compras); Industrial usa el ÚLTIMO valor ingresado, pisando el anterior (no promedia). Compras NUNCA se ve afectado por este campo -- la compra de insumos/materia prima es un módulo de costeo aparte, fuera de alcance hoy.", max_length=20),
        ),
    ]
