# Generated by Django 5.2.16 on 2026-09-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0008_empresa_tipo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_host',
            field=models.CharField(blank=True, help_text='Servidor SMTP saliente (ej. smtp.gmail.com). Vacío = usa la configuración del servidor (.env).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_password',
            field=models.CharField(blank=True, help_text="Contraseña o 'contraseña de aplicación' de esa cuenta. No se muestra en pantalla una vez guardada.", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Cuenta de correo desde la que se envían las facturas.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
