# Generated by Django 5.2.16 on 2026-09-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0009_empresa_email_host_empresa_email_host_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='formato_factura',
            field=models.CharField(choices=[('CARTA', 'Tamaño Carta (hoja A4/carta)'), ('TERMICO', 'Rollo térmico/químico (58mm, impresora de tickets)')], default='TERMICO', help_text='Formato que se usa para mostrar, descargar, y enviar por correo/WhatsApp las facturas. Por defecto Rollo térmico (el que ya usaba el sistema en la caja).', max_length=10),
        ),
    ]
