# Generated by Django 5.2.16 on 2026-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0010_empresa_formato_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección principal de la empresa. Aparece en el encabezado de las facturas.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial')], default='COMERCIAL', help_text='Afecta solo el costeo de Producción Interna: Comercial promedia el costo, Industrial usa el último valor cargado.', max_length=20),
        ),
    ]
