# Generated by Django 5.2.16 on 2026-09-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0011_empresa_direccion_alter_empresa_tipo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUFDVigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_punto_venta', models.PositiveIntegerField(default=0)),
                ('cufd', models.CharField(max_length=150)),
                ('codigo_control', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cufd_vigentes', to='fe.sucursal')),
            ],
            options={
                'verbose_name': 'CUFD Vigente (caché offline)',
                'verbose_name_plural': 'CUFD Vigentes (caché offline)',
                'unique_together': {('sucursal', 'codigo_punto_venta')},
            },
        ),
    ]
