# Generated by Django 4.2.6 on 2024-01-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0007_comprasenc_comprasdet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={},
        ),
    ]
