# Generated by Django 5.2.16 on 2026-08-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0008_alter_comprasdet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compras'},
        ),
    ]
