# Generated by Django 5.2.16 on 2026-08-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0009_alter_comprasdet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
