# Generated by Django 5.2.16 on 2026-08-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0010_alter_proveedor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
