# Generated by Django 5.2.16 on 2026-09-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0011_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasenc',
            options={'permissions': [('eliminar_comprasenc', 'Permiso para eliminar una compra completa')], 'verbose_name': 'Encabezado Compra', 'verbose_name_plural': 'Encabezado Compras'},
        ),
    ]
