# Generated by Django 5.2.16 on 2026-09-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0012_alter_comprasenc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasenc',
            options={'permissions': [('eliminar_comprasenc', 'Permiso para eliminar una compra completa'), ('editar_compra_dia_cerrado', 'Permiso para crear o editar una compra en un día ya cerrado')], 'verbose_name': 'Encabezado Compra', 'verbose_name_plural': 'Encabezado Compras'},
        ),
    ]
