# Generated by Django 5.2.16 on 2026-09-10 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0013_alter_comprasenc_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasenc',
            options={'permissions': [('eliminar_comprasenc', 'Permiso para eliminar una compra completa'), ('editar_compra_dia_cerrado', 'Permiso para crear o editar una compra en un día ya cerrado'), ('eliminar_compra_mes_vigente', 'Permiso para eliminar compras de cualquier día del mes en curso (no solo el día de hoy)')], 'verbose_name': 'Encabezado Compra', 'verbose_name_plural': 'Encabezado Compras'},
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='costo_promedio_antes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprasdet',
            name='usuario_reversion',
            field=models.ForeignKey(blank=True, help_text='Usuario que autorizó esta línea como reversión de otra. Vacío si la línea no es una reversión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
