# Generated by Django 5.2.16 on 2026-09-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0014_alter_comprasenc_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasdet',
            old_name='costo_promedio_antes',
            new_name='costo_actual_antes',
        ),
    ]
