# Generated by Django 5.2.16 on 2026-09-21 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0015_rename_costo_promedio_antes_comprasdet_costo_actual_antes'),
        ('fe', '0011_empresa_direccion_alter_empresa_tipo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasenc',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fe.sucursal'),
        ),
    ]
