# Generated by Django 5.2.16 on 2026-09-25 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0016_comprasenc_sucursal'),
        ('fe', '0012_cufdvigente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Vacío = proveedor compartido con todas las sucursales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='fe.sucursal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('sucursal', 'descripcion'), name='proveedor_descripcion_unica_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nit'), name='proveedor_nit_unico_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('sucursal__isnull', True)), fields=('descripcion',), name='proveedor_descripcion_unica_compartido'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(condition=models.Q(('sucursal__isnull', True)), fields=('nit',), name='proveedor_nit_unico_compartido'),
        ),
    ]
