# Generated by Django 5.2.16 on 2026-09-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0017_proveedor_por_sucursal'),
        ('fe', '0012_cufdvigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece este proveedor (cada sucursal maneja sus propios proveedores).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='fe.sucursal'),
        ),
    ]
