# Generated by Django 4.2.6 on 2023-10-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_remove_cliente_ci_remove_cliente_nit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
