# Generated by Django 4.2.6 on 2023-10-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_alter_cliente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
