# Generated by Django 4.2.2 on 2023-09-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0004_rename_nit_proveedor_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.FloatField(unique=True),
        ),
    ]
