# Generated by Django 5.2.16 on 2026-09-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fe', '0011_empresa_direccion_alter_empresa_tipo_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal donde opera este usuario. Vacío = se resuelve solo si la empresa tiene una única sucursal; si tiene varias, hay que asignarla acá explícitamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fe.sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
