# Generated by Django 5.2.16 on 2026-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='alcance',
            field=models.CharField(choices=[('TODAS', 'Todas las sucursales'), ('SUCURSAL', 'Solo su sucursal asignada')], default='TODAS', help_text="Que datos ve este usuario en listados y reportes (facturas, compras, inventario, dashboard...). 'Solo su sucursal asignada' exige tener una sucursal cargada arriba. Los superusuarios siempre ven todo.", max_length=10),
        ),
    ]
