# Generated by Django 5.2.16 on 2026-07-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('exitosa', models.BooleanField(default=False)),
                ('catalogos_sincronizados', models.PositiveIntegerField(default=0, help_text='Cuántos de los 16 catálogos se actualizaron correctamente en esta corrida.')),
                ('total_codigos_actualizados', models.PositiveIntegerField(default=0, help_text='Suma de códigos nuevos o modificados across todos los catálogos.')),
                ('mensaje', models.TextField(blank=True, help_text='Detalle del error si exitosa=False, o resumen si exitosa=True.')),
            ],
            options={
                'verbose_name': 'Log de Sincronización SIN',
                'verbose_name_plural': 'Logs de Sincronización SIN',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoSIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_catalogo', models.CharField(choices=[('ACTIVIDADES', 'Códigos de Actividades'), ('ACT_DOC_SECTOR', 'Actividades Documento Sector'), ('LEYENDAS', 'Leyendas Facturas'), ('MENSAJES', 'Mensajes Servicios'), ('EVENTOS', 'Eventos Significativos'), ('MOTIVOS_ANULACION', 'Motivos Anulación'), ('PAIS', 'País Origen'), ('TIPO_DOC_IDENTIDAD', 'Tipo Documento Identidad'), ('TIPO_DOC_SECTOR', 'Tipo Documento Sector'), ('TIPO_EMISION', 'Tipo Emisión'), ('TIPO_HABITACION', 'Tipo Habitación'), ('TIPO_METODO_PAGO', 'Tipo Método Pago'), ('TIPO_MONEDA', 'Tipo Moneda'), ('TIPO_PUNTO_VENTA', 'Tipo Punto de Venta'), ('TIPO_FACTURA', 'Tipo Factura'), ('TIPO_UNIDAD_MEDIDA', 'Tipo Unidad de Medida')], db_index=True, help_text='A qué catálogo del SIN pertenece este código.', max_length=30)),
                ('codigo', models.CharField(help_text='Código tal como lo entrega el SIN (se guarda como texto aunque sea numérico, por seguridad ante ceros a la izquierda u otros formatos).', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('vigente', models.BooleanField(default=True, help_text='Se marca False si una sincronización posterior ya no trae este código (baja lógica, nunca se borra el histórico).')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True, help_text='Última vez que este registro fue confirmado por el SIN.')),
            ],
            options={
                'verbose_name': 'Catálogo SIN',
                'verbose_name_plural': 'Catálogos SIN',
                'ordering': ['tipo_catalogo', 'codigo'],
                'unique_together': {('tipo_catalogo', 'codigo')},
            },
        ),
    ]
