# Generated by Django 5.2.16 on 2026-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogosin',
            name='tipo_catalogo',
            field=models.CharField(choices=[('ACTIVIDADES', 'Códigos de Actividades'), ('ACT_DOC_SECTOR', 'Actividades Documento Sector'), ('LEYENDAS', 'Leyendas Facturas'), ('MENSAJES', 'Mensajes Servicios'), ('EVENTOS', 'Eventos Significativos'), ('MOTIVOS_ANULACION', 'Motivos Anulación'), ('PAIS', 'País Origen'), ('TIPO_DOC_IDENTIDAD', 'Tipo Documento Identidad'), ('TIPO_DOC_SECTOR', 'Tipo Documento Sector'), ('TIPO_EMISION', 'Tipo Emisión'), ('TIPO_HABITACION', 'Tipo Habitación'), ('TIPO_METODO_PAGO', 'Tipo Método Pago'), ('TIPO_MONEDA', 'Tipo Moneda'), ('TIPO_PUNTO_VENTA', 'Tipo Punto de Venta'), ('TIPO_FACTURA', 'Tipo Factura'), ('TIPO_UNIDAD_MEDIDA', 'Tipo Unidad de Medida'), ('PRODUCTOS_SERVICIOS', 'Productos y Servicios')], db_index=True, help_text='A qué catálogo del SIN pertenece este código.', max_length=30),
        ),
    ]
