# Generated by Django 5.2.16 on 2026-08-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_catalogosin_tipo_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogosin',
            name='codigo_actividad',
            field=models.CharField(blank=True, db_index=True, help_text='Solo aplica al catálogo PRODUCTOS_SERVICIOS: código de actividad económica (CAEB) a la que el SIN asocia este producto/servicio. Necesario para filtrar el catálogo en la pantalla de Homologación de Productos.', max_length=20, null=True),
        ),
    ]
