# Generated by Django 5.2.16 on 2026-08-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_catalogosin_codigo_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDocumentoSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.CharField(db_index=True, max_length=20)),
                ('codigo_documento_sector', models.PositiveIntegerField()),
                ('tipo_documento_sector', models.CharField(help_text="Código corto que identifica el tipo (ej. 'FCV', 'FAC_SEG') -- no es una descripción larga, el SIN no entrega una para este catálogo.", max_length=20)),
                ('vigente', models.BooleanField(default=True, help_text='Se marca False si una sincronización posterior ya no trae esta combinación (baja lógica, mismo criterio que CatalogoSIN).')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad ↔ Documento Sector',
                'verbose_name_plural': 'Actividades ↔ Documento Sector',
                'ordering': ['codigo_actividad', 'codigo_documento_sector'],
                'unique_together': {('codigo_actividad', 'codigo_documento_sector')},
            },
        ),
    ]
