# Generated by Django 5.2.16 on 2026-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='actividad_economica_sin',
            field=models.CharField(blank=True, help_text='Código CAEB de actividad económica (catálogo ACTIVIDADES en app catalogos) asociado a este producto.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_producto_sin',
            field=models.CharField(blank=True, help_text='Código de producto/servicio SIN (catálogo PRODUCTOS_SERVICIOS en app catalogos) asociado a este producto.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='codigo_sin',
            field=models.CharField(blank=True, help_text="Código del catálogo SIN 'TIPO_UNIDAD_MEDIDA' (ver app catalogos). Necesario para facturación electrónica.", max_length=10, null=True),
        ),
    ]
