# Generated by Django 5.2.16 on 2026-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_producto_actividad_economica_sin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_promocional_pct',
            field=models.FloatField(default=0, help_text='Porcentaje de descuento promocional para este producto (ej. 15 = 15%). Se combina/suma con el descuento del cliente, si lo tiene. 0 = sin promocion.'),
        ),
    ]
