# Generated by Django 5.2.16 on 2026-08-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_producto_descuento_promocional_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_vigencia_desde',
            field=models.DateField(blank=True, help_text="Si se deja vacio junto con 'hasta', el descuento no tiene limite de fecha (siempre activo mientras el % sea > 0).", null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento_vigencia_hasta',
            field=models.DateField(blank=True, help_text='Fecha en que la promocion deja de aplicarse automaticamente.', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento_promocional_pct',
            field=models.FloatField(default=0, help_text='Porcentaje de descuento promocional para este producto (ej. 15 = 15%). Solo se aplica dentro del rango de vigencia (si se define). Si el cliente tambien tiene descuento, se aplica el MAYOR de los dos, no se suman.'),
        ),
    ]
