# Generated by Django 5.2.16 on 2026-08-12 14:39

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_producto_descuento_vigencia_desde_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('gestionar_precios_tc', 'Puede gestionar Tipo de Cambio y Revisión de Precios')], 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_referencia_usd',
            field=models.FloatField(blank=True, help_text='Costo del producto en USD, para productos importados. Vacio = producto sin costo en moneda extranjera.', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_deseado_pct',
            field=models.FloatField(default=0, help_text='Margen deseado sobre el costo en USD convertido a bolivianos (ej. 30 = 30%). 0 = sin margen definido.'),
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(unique=True)),
                ('valor', models.FloatField(help_text='Bolivianos por 1 dolar (ej. 9.73).')),
                ('fuente', models.CharField(blank=True, default='BCB Oficial', max_length=100)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Cambio',
                'verbose_name_plural': 'Tipos de Cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('precio_anterior', models.FloatField()),
                ('precio_nuevo', models.FloatField()),
                ('motivo', models.CharField(blank=True, default='Ajuste por tipo de cambio', max_length=250)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='inv.producto')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_cambio_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.tipocambio')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fc'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_cambio_referencia',
            field=models.ForeignKey(blank=True, help_text='Tipo de cambio con el que se fijo el precio actual de este producto. Se actualiza solo (no editable a mano) cada vez que se aplica un ajuste de precio desde la pantalla de Revision de Precios.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.tipocambio'),
        ),
    ]
