# Generated by Django 5.2.16 on 2026-09-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_alter_producto_options_producto_costo_referencia_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.FloatField(default=0, help_text='Costo Promedio Ponderado, calculado automáticamente con cada compra registrada. No editable a mano.'),
        ),
    ]
