# Generated by Django 5.2.16 on 2026-09-13 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_producto_costo_promedio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='costo_promedio',
            new_name='costo_actual',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='costo_referencia_usd',
            new_name='precio_referencia_usd',
        ),
        migrations.CreateModel(
            name='AjusteInventarioEnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'permissions': [('eliminar_ajusteinventarioenc', 'Permiso para eliminar un ajuste de inventario completo'), ('cargar_inventario_inicial', 'Permiso para hacer la carga inicial masiva de inventario por Excel')],
            },
        ),
        migrations.CreateModel(
            name='AjusteInventarioDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.FloatField()),
                ('sub_total', models.FloatField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.producto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.ajusteinventarioenc')),
            ],
            options={
                'verbose_name': 'Detalle de Ajuste de Inventario',
                'verbose_name_plural': 'Detalles de Ajuste de Inventario',
            },
        ),
        migrations.CreateModel(
            name='MotivoAjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('es_entrada', models.BooleanField(default=True, help_text='True = este motivo SUMA stock (Carga Inicial, Producción Interna). False = resta stock -- reservado para cuando se agregue el caso de mermas/correcciones a la baja; NO USADO en esta version.')),
                ('afecta_costo_actual', models.BooleanField(default=True, help_text='True = las entradas con este motivo recalculan Producto.costo_actual. Dejar en True para Carga Inicial y Producción Interna.')),
                ('es_produccion_interna', models.BooleanField(default=False, help_text="Marca el motivo 'Producción Interna' especificamente -- es el UNICO que se ve afectado por Empresa.tipo_empresa. Los demas motivos (ej. Carga Inicial) siempre usan Promedio Ponderado, sin importar el tipo de empresa.")),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivo de Ajuste de Inventario',
                'verbose_name_plural': 'Motivos de Ajuste de Inventario',
            },
        ),
        migrations.AddField(
            model_name='ajusteinventarioenc',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.motivoajusteinventario'),
        ),
    ]
