# Generated by Django 5.2.16 on 2026-09-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0012_rename_costo_promedio_producto_costo_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_actual',
            field=models.FloatField(default=0, help_text='Costo actual del producto, calculado automáticamente con cada entrada registrada (compra o ajuste de inventario). En empresas Comerciales es un Promedio Ponderado; en Industriales, el último valor de Producción Interna, sin promediar. No editable a mano.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_referencia_usd',
            field=models.FloatField(blank=True, help_text='Precio de referencia del producto en USD, para productos importados -- base para sugerir un precio de venta (ver Revisión de Precios). Vacío = producto sin referencia en moneda extranjera.', null=True),
        ),
    ]
