# Generated by Django 5.2.16 on 2026-09-25 11:55

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe', '0012_cufdvigente'),
        ('inv', '0014_ajusteinventarioenc_sucursal_transferenciastockenc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialprecioproducto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fe.sucursal'),
        ),
        migrations.CreateModel(
            name='PrecioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('precio', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_sucursal', to='inv.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_producto', to='fe.sucursal')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Precio por Sucursal',
                'verbose_name_plural': 'Precios por Sucursal',
                'permissions': [('gestionar_precios_sucursal', 'Puede fijar el precio de venta local de una sucursal')],
                'constraints': [models.UniqueConstraint(fields=('producto', 'sucursal'), name='precio_unico_por_producto_sucursal')],
            },
        ),
    ]
