# Generated by Django 4.2.6 on 2023-10-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='razon',
        ),
    ]
