# Generated by Django 5.2.16 on 2026-08-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0008_alter_facturaenc_options_facturaenc_anulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='codigo_motivo_anulacion_sin',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Codigo del catalogo MOTIVOS_ANULACION (app catalogos) enviado al SIN.', null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='codigo_recepcion_sin',
            field=models.CharField(blank=True, help_text='codigoRecepcion devuelto por el SIN al recibir la factura o el paquete.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='cufd',
            field=models.CharField(blank=True, help_text='CUFD vigente usado al momento de la emision. Se guarda para auditoria.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='estado_sin',
            field=models.CharField(choices=[('no_enviada', 'No enviada al SIN'), ('pendiente', 'Pendiente (paquete en revision)'), ('validada', 'Validada por el SIN'), ('observada', 'Observada por el SIN'), ('anulada', 'Anulada ante el SIN'), ('revertida', 'Anulacion revertida ante el SIN')], default='no_enviada', help_text="Estado real confirmado por el SIN (distinto de 'anulado', que es la intencion local).", max_length=15),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_anulacion_sin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_hora_envio_sin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_reversion_sin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='mensaje_sin',
            field=models.TextField(blank=True, help_text='mensajesList devuelto por el SIN (errores/advertencias), si los hubo.', null=True),
        ),
    ]
