# Generated by Django 5.2.16 on 2026-08-06 16:20

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0009_facturaenc_codigo_motivo_anulacion_sin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('cerrado', 'Cerrado'), ('cerrado_con_pendientes', 'Cerrado con pendientes (forzado por supervisor)')], default='cerrado', max_length=25)),
                ('fecha_hora_cierre', models.DateTimeField(auto_now_add=True)),
                ('total_facturado', models.FloatField(default=0)),
                ('cantidad_facturas', models.IntegerField(default=0)),
                ('facturas_pendientes_sin', models.IntegerField(default=0, help_text='Cantidad de facturas que quedaron sin resolver ante el SIN al momento del cierre (solo > 0 si se forzo el cierre con pendientes).')),
                ('observaciones', models.TextField(blank=True, help_text='Obligatorio si el cierre se forzo con facturas pendientes.', null=True)),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Día',
                'verbose_name_plural': 'Cierres de Día',
                'permissions': [('gestionar_cierre_dia', 'Permiso para gestionar el Cierre de Día')],
            },
        ),
    ]
