# Generated by Django 5.2.16 on 2026-08-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0010_cierredia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descuento_autorizado_pct',
            field=models.FloatField(default=0, help_text='Porcentaje de descuento pre-aprobado para este cliente (ej. 10 = 10%). Se aplica automaticamente en cada venta, sin que el cajero decida nada. 0 = sin descuento.'),
        ),
    ]
