# Generated by Django 5.2.16 on 2026-08-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0011_cliente_descuento_autorizado_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
