# Generated by Django 5.2.16 on 2026-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0012_alter_cliente_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='xml_firmado',
            field=models.TextField(blank=True, help_text='XML firmado tal cual se envio al SIN, guardado para poder descargarlo despues (auditoria, contadores, etc.).', null=True),
        ),
    ]
