# Generated by Django 5.2.16 on 2026-08-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0013_facturaenc_xml_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='codigo_metodo_pago',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
