# Generated by Django 5.2.16 on 2026-08-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0014_facturaenc_codigo_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
