# Generated by Django 5.2.16 on 2026-08-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0015_alter_cliente_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('QR', 'QR'), ('CHEQUE', 'Cheque'), ('VALES', 'Vales'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('DEPOSITO', 'Depósito en Cuenta'), ('SWIFT', 'Transferencia Swift'), ('GIFT_CARD', 'Gift Card'), ('BILLETERA_MOVIL', 'Billetera Móvil'), ('PAGO_ONLINE', 'Pago Online'), ('DEBITO_AUTOMATICO', 'Débito Automático')], default='EFECTIVO', help_text='Elegido por el cajero. El codigo real que se le reporta al SIN se calcula solo, ver FORMA_PAGO_A_CODIGO_SIN.', max_length=20),
        ),
        migrations.AlterField(
            model_name='cierredia',
            name='facturas_pendientes_sin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cierredia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='codigo_metodo_pago',
            field=models.CharField(default='1', help_text="Codigo real del catalogo SIN TIPO_METODO_PAGO, calculado automaticamente a partir de 'forma_pago' -- no se edita directamente.", max_length=10),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='codigo_motivo_anulacion_sin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='codigo_recepcion_sin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='cufd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='estado_sin',
            field=models.CharField(choices=[('no_enviada', 'No enviada al SIN'), ('pendiente', 'Pendiente (paquete en revision)'), ('validada', 'Validada por el SIN'), ('observada', 'Observada por el SIN'), ('anulada', 'Anulada ante el SIN'), ('revertida', 'Anulacion revertida ante el SIN')], default='no_enviada', max_length=15),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='mensaje_sin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='xml_firmado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
