# Generated by Django 5.2.16 on 2026-08-17 20:49

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0016_facturaenc_forma_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Encabezado'), ('anular_facturaenc', 'Permiso para Anular Facturas'), ('gestionar_creditos', 'Permiso para gestionar ventas a credito y cobranza')], 'verbose_name': 'Encabezado Factura', 'verbose_name_plural': 'Encabezado Facturas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='autorizado_credito',
            field=models.BooleanField(default=False, help_text="Si esta marcado, este cliente puede elegir 'Crédito' como forma de pago al facturar."),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.FloatField(default=0, help_text='Monto maximo de saldo pendiente permitido para este cliente (suma de todas sus facturas a credito sin pagar por completo). 0 = sin limite definido (bloquea cualquier venta a credito hasta que se cargue un limite real).'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plazo_credito_dias',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(7, '7 días'), (15, '15 días'), (30, '30 días')], help_text='Plazo de pago para este cliente. Se aplica automaticamente a todas sus ventas a credito (no se elige por venta).', null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text="Se calcula solo (fecha de la venta + plazo del cliente) cuando forma_pago='CREDITO'.", null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='saldo_pendiente',
            field=models.FloatField(default=0, help_text="Se inicializa en 'total' al guardar una venta a credito, y se descuenta con cada Pago (abono) registrado."),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='descuento_autorizado_pct',
            field=models.FloatField(default=0, help_text='Porcentaje de descuento pre-aprobado para este cliente (ej. 10 = 10%). Se aplica automaticamente en cada venta.'),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='codigo_metodo_pago',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('QR', 'QR'), ('CHEQUE', 'Cheque'), ('VALES', 'Vales'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('DEPOSITO', 'Depósito en Cuenta'), ('SWIFT', 'Transferencia Swift'), ('GIFT_CARD', 'Gift Card'), ('BILLETERA_MOVIL', 'Billetera Móvil'), ('PAGO_ONLINE', 'Pago Online'), ('DEBITO_AUTOMATICO', 'Débito Automático'), ('CREDITO', 'Crédito (venta a plazo)')], default='EFECTIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('QR', 'QR'), ('TRANSFERENCIA', 'Transferencia Bancaria')], default='EFECTIVO', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='fac.facturaenc')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago (Abono)',
                'verbose_name_plural': 'Pagos (Abonos)',
                'ordering': ['-fecha'],
            },
        ),
    ]
