# Generated by Django 5.2.16 on 2026-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0017_alter_facturaenc_options_cliente_autorizado_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='numero_tarjeta',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta. Requerido por el SIN cuando la forma de pago es Tarjeta de Débito o Crédito.', max_length=4, null=True),
        ),
    ]
