# Generated by Django 5.2.16 on 2026-08-20 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0018_facturaenc_numero_tarjeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='usuario_reversion',
            field=models.ForeignKey(blank=True, help_text='Supervisor que autorizó esta línea como reversión de otra. Vacío si esta línea no es una reversión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
