# Generated by Django 5.2.16 on 2026-08-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0019_facturadet_usuario_reversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_reversion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_reversion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='revertido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario_reversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_revertidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
