# Generated by Django 5.2.16 on 2026-08-28 22:49

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0020_pago_fecha_reversion_pago_motivo_reversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(help_text='Motivo de la correccion, para auditoria interna -- el XSD de este documento no tiene un campo de motivo propio ante el SIN.', max_length=250)),
                ('cuf', models.CharField(blank=True, max_length=100, null=True)),
                ('cufd', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_total_original', models.FloatField(help_text='Total de la factura original (montoTotalOriginal ante el SIN).')),
                ('monto_total_devuelto', models.FloatField(help_text='Monto devuelto -- en esta primera version, siempre igual al total de la factura original (devolucion total, no parcial).')),
                ('monto_descuento_credito_debito', models.FloatField(default=0, help_text='Prorrateo del descuento adicional de la factura original. Nuestro sistema nunca usa descuentoAdicional a nivel factura (los descuentos ya estan netos en cada linea, ver _armar_cabecera en fe/services.py), asi que este campo queda en 0 en la practica.')),
                ('monto_efectivo_credito_debito', models.FloatField(help_text='13% (IVA) del monto total devuelto -- calculado automaticamente, segun exige el XSD oficial de este documento.')),
                ('estado_sin', models.CharField(choices=[('no_enviada', 'Sin Emitir al SIN'), ('pendiente', 'Pendiente SIN'), ('validada', 'Validada SIN'), ('observada', 'Observada SIN')], default='no_enviada', max_length=20)),
                ('codigo_recepcion_sin', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje_sin', models.TextField(blank=True, null=True)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('factura_original', models.ForeignKey(help_text='Factura que esta Nota de Credito-Debito corrige/ajusta.', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_debito', to='fac.facturaenc')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_autorizacion', models.ForeignKey(blank=True, help_text='Supervisor que autorizo la emision de esta NCD.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_debito_autorizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Crédito-Débito',
                'verbose_name_plural': 'Notas de Crédito-Débito',
                'ordering': ['-fecha'],
            },
        ),
    ]
