# Generated by Django 5.2.16 on 2026-08-31 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0021_notacreditodebito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierredia',
            options={'permissions': [('gestionar_cierre_dia', 'Permiso para gestionar el Cierre de Día'), ('forzar_cierre_dia', 'Permiso para forzar el Cierre de Día con facturas pendientes')], 'verbose_name': 'Cierre de Día', 'verbose_name_plural': 'Cierres de Día'},
        ),
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Encabezado'), ('anular_facturaenc', 'Permiso para Anular Facturas'), ('gestionar_creditos', 'Permiso para gestionar ventas a credito y cobranza'), ('eliminar_facturaenc', 'Permiso para eliminar una factura completa'), ('ver_creditos', 'Permiso para ver Cartera de Creditos y Kardex de Cliente (solo lectura)'), ('ver_reportes_financieros', 'Permiso para ver Cierre de Ventas y Cierre de Caja')], 'verbose_name': 'Encabezado Factura', 'verbose_name_plural': 'Encabezado Facturas'},
        ),
    ]
