# Generated by Django 5.2.16 on 2026-09-15 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0022_alter_cierredia_options_alter_facturaenc_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditodebito',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='codigo_motivo_anulacion_sin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='fecha_anulacion_sin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notacreditodebito',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notacreditodebito',
            name='estado_sin',
            field=models.CharField(choices=[('no_enviada', 'Sin Emitir al SIN'), ('pendiente', 'Pendiente SIN'), ('validada', 'Validada SIN'), ('observada', 'Observada SIN'), ('anulada', 'Anulada ante el SIN')], default='no_enviada', max_length=20),
        ),
    ]
