# Generated by Django 5.2.16 on 2026-09-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0023_notacreditodebito_anulada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditodebito',
            name='fecha_reversion_sin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notacreditodebito',
            name='estado_sin',
            field=models.CharField(choices=[('no_enviada', 'Sin Emitir al SIN'), ('pendiente', 'Pendiente SIN'), ('validada', 'Validada SIN'), ('observada', 'Observada SIN'), ('anulada', 'Anulada ante el SIN'), ('revertida', 'Anulación revertida ante el SIN')], default='no_enviada', max_length=20),
        ),
    ]
