# Generated by Django 5.2.16 on 2026-09-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0024_notacreditodebito_fecha_reversion_sin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='codigo_control',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
