# Generated by Django 5.2.16 on 2026-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0025_facturaenc_codigo_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditodebito',
            name='codigo_control',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
