# Generated by Django 5.2.16 on 2026-09-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0026_notacreditodebito_codigo_control'),
        ('fe', '0011_empresa_direccion_alter_empresa_tipo_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fe.sucursal'),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fe.sucursal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('sucursal', 'ci'), name='cliente_unico_ci_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('sucursal', 'nit'), name='cliente_unico_nit_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('sucursal', 'razon'), name='cliente_unico_razon_por_sucursal'),
        ),
    ]
