# Generated by Django 5.2.16 on 2026-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0027_cliente_sucursal_facturaenc_sucursal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='leyenda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
