# Generated by Django 5.2.16 on 2026-09-21 13:36

import django.db.models.deletion
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0028_facturaenc_leyenda'),
        ('fe', '0012_cufdvigente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSignificativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('codigo_punto_venta', models.PositiveIntegerField(default=0)),
                ('codigo_motivo', models.PositiveSmallIntegerField(help_text='Código del catálogo SIN EVENTOS_SIGNIFICATIVOS (ej. 2 = Inaccesibilidad al servicio web de la Administración Tributaria).')),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_hora_inicio', models.DateTimeField(help_text='Momento de la primera factura offline de este evento.')),
                ('fecha_hora_fin', models.DateTimeField(blank=True, help_text='Se completa recién al cerrar el evento (Fase B), cuando vuelve la conexión.', null=True)),
                ('cufd_evento', models.CharField(blank=True, max_length=150, null=True)),
                ('cufd_reporte', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_recepcion_evento_significativo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_evento', models.CharField(choices=[('abierto', 'Abierto (contingencia en curso)'), ('cerrado', 'Cerrado (reportado al SIN)')], default='abierto', max_length=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_significativos', to='fe.sucursal')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Significativo',
                'verbose_name_plural': 'Eventos Significativos',
            },
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='evento_significativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='fac.eventosignificativo'),
        ),
        migrations.CreateModel(
            name='PaqueteFacturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('cantidad_facturas', models.PositiveIntegerField(default=0)),
                ('hash_archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_recepcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_envio', models.DateTimeField(help_text='48 horas desde fecha_hora_fin del evento (checklist SIN Fase II, punto 8).')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('mensaje_sin', models.TextField(blank=True, null=True)),
                ('estado_paquete', models.CharField(choices=[('en_armado', 'En armado'), ('enviado', 'Enviado, esperando validación'), ('validado', 'Validado por el SIN'), ('rechazado', 'Rechazado por el SIN')], default='en_armado', max_length=15)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='fac.eventosignificativo')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paquete de Facturas (contingencia)',
                'verbose_name_plural': 'Paquetes de Facturas (contingencia)',
            },
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='fac.paquetefacturas'),
        ),
    ]
