# Generated by Django 5.2.16 on 2026-09-25 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0029_eventosignificativo_facturaenc_evento_significativo_and_more'),
        ('fe', '0012_cufdvigente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierredia',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_dia', to='fe.sucursal'),
        ),
        migrations.AlterField(
            model_name='cierredia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='cierredia',
            constraint=models.UniqueConstraint(fields=('fecha', 'sucursal'), name='cierre_dia_unico_por_sucursal'),
        ),
    ]
